### ISSUE TITLE
conda install errors

### ISSUE THREAD

**Issue by hyphaltip** [AstrobioMike/GToTree#11]
running in anaconda3

==> script messages <==
<None>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "/opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "/opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/lib/python3.6/site-packages/conda/cli/install.py", line 253, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/lib/python3.6/site-packages/conda/cli/install.py", line 282, in handle_txn
    unlink_link_transaction.execute()
  File "/opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/lib/python3.6/site-packages/conda/core/link.py", line 229, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/lib/python3.6/site-packages/conda/core/link.py", line 521, in _execute
    rollback_excs,
conda.CondaMultiError: post-link script failed for package astrobiomike::gtotree-1.4.7-py37_1
running your command again with `-v` will provide additional information
location of failed script: /opt/linux/centos/7.x/x86_64/pkgs/anaconda3/4.5.4/envs/gtotree/bin/.gtotree-post-link.sh
==> script messages <==
<None>

**Comment by AstrobioMike** [comment]
Noooo, ha. Thanks for writing in about it, @hyphaltip!

Can you do me a favor and see if you get the same result by trying to install this previous build, can be done like so:

```
conda create -y -n gtotree-old-build -c conda-forge -c bioconda -c astrobiomike gtotree=1.4.7=py37_0
```

Also, it says at the start up there "during handling of the above exception, another exception occurred". Was there something else that popped up before this? 

Last, it seems a little weird to me it says it's working in a python3.6 environment when it should be a 3.7, but maybe that's just my slight lack of familiarity with how anaconda organizes things. Were you initially running the install command like this?

```
conda create -y -n gtotree -c conda-forge -c bioconda -c astrobiomike gtotree
```

Thanks again for letting me know!
