### ISSUE TITLE
GToTree fails to download accessions after updating

### ISSUE THREAD

**Issue by anonymous7002** [AstrobioMike/GToTree#43]
```
     Genome: GCF_002263795.1
  ********************************** NOTICE **********************************
   GCF_002263795.1 did not download properly :(

   Reported in "E/run_files/NCBI_accessions_not_downloaded.txt"
  ****************************************************************************


gzip: 1629016998.gtotree.tmpdir/GCF_002263795.1_genes2.tmp.gz: invalid compressed data--format violated
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/gtotree/bin/gtt-rename-fasta-headers", line 21, in <module>
    in_fasta = open(args.input_fasta, "r")
FileNotFoundError: [Errno 2] No such file or directory: '1629016998.gtotree.tmpdir/GCF_002263795.1_genes2.tmp'
   --------------------------------------------------------------------------

     Genome: GCF_002863925.1
  ********************************** NOTICE **********************************
   GCF_002863925.1 did not download properly :(

   Reported in "E/run_files/NCBI_accessions_not_downloaded.txt"
  ****************************************************************************


gzip: 1629016998.gtotree.tmpdir/GCF_002863925.1_genes2.tmp.gz: invalid compressed data--format violated
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/gtotree/bin/gtt-rename-fasta-headers", line 21, in <module>
    in_fasta = open(args.input_fasta, "r")
FileNotFoundError: [Errno 2] No such file or directory: '1629016998.gtotree.tmpdir/GCF_002863925.1_genes2.tmp'
   --------------------------------------------------------------------------

     Genome: GCF_002880755.1
  ********************************** NOTICE **********************************
   GCF_002880755.1 did not download properly :(

   Reported in "E/run_files/NCBI_accessions_not_downloaded.txt"
  ****************************************************************************


gzip: 1629016998.gtotree.tmpdir/GCF_002880755.1_genes2.tmp.gz: invalid compressed data--format violated
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/gtotree/bin/gtt-rename-fasta-headers", line 21, in <module>
    in_fasta = open(args.input_fasta, "r")
FileNotFoundError: [Errno 2] No such file or directory: '1629016998.gtotree.tmpdir/GCF_002880755.1_genes2.tmp'
   --------------------------------------------------------------------------

     Genome: GCF_002880775.1
  ********************************** NOTICE **********************************
   GCF_002880775.1 did not download properly :(

   Reported in "E/run_files/NCBI_accessions_not_downloaded.txt"
  ****************************************************************************


gzip: 1629016998.gtotree.tmpdir/GCF_002880775.1_genes2.tmp.gz: invalid compressed data--format violated
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/gtotree/bin/gtt-rename-fasta-headers", line 21, in <module>
    in_fasta = open(args.input_fasta, "r")
FileNotFoundError: [Errno 2] No such file or directory: '1629016998.gtotree.tmpdir/GCF_002880775.1_genes2.tmp'
   --------------------------------------------------------------------------

     Genome: GCF_008728515.1
  ********************************** NOTICE **********************************
   GCF_008728515.1 did not download properly :(

   Reported in "E/run_files/NCBI_accessions_not_downloaded.txt"
  ****************************************************************************


gzip: 1629016998.gtotree.tmpdir/GCF_008728515.1_genes2.tmp.gz: invalid compressed data--format violated
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/gtotree/bin/gtt-rename-fasta-headers", line 21, in <module>
    in_fasta = open(args.input_fasta, "r")
FileNotFoundError: [Errno 2] No such file or directory: '1629016998.gtotree.tmpdir/GCF_008728515.1_genes2.tmp'
```
These started to appear after updating to 1.6.10, and didn't occur in 1.6.00.

**Comment by AstrobioMike** [comment]
Unfortunately I can't recreate this problem on mac or linux, and I don't have a windows and therefore WSL to test on. 

Can you attach the input accessions file you're using and the full run log (or email if you prefer: MikeLee<at>bmsis<dot>org)? (I know this is independent of the other issue: https://github.com/AstrobioMike/GToTree/issues/42#issuecomment-899008607)

**Comment by AstrobioMike** [comment]
closing this for now. Feel free to re-open if needed, of course :)
