### ISSUE TITLE
Issue with using GTDB

### ISSUE THREAD

**Issue by Ahmed-Shibl** [AstrobioMike/GToTree#71]
Thanks for this extremely useful tool!

I'm trying to use GToTree ( latest version v1.7.05) with the Genome Taxonomy Database (GTDB) and ran into an error I couldn't find a solution for:

This is the command I ran to search the GTDB based on taxonomy:

`gtt-get-accessions-from-GTDB -t Actinobacteriota --GTDB-representatives-only --get-taxon-counts --store-GTDB-metadata-in-current-working-dir --do-not-check-GTDB-version`

and this is the error I get:

```
  Downloading and parsing archaeal and bacterial metadata tables from
  GTDB...
Traceback (most recent call last):
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/bin/gtt-get-accessions-from-GTDB", line 606, in <module>
    main()
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/bin/gtt-get-accessions-from-GTDB", line 94, in main
    gtdb_tab = get_gtdb_tab(args.do_not_check_GTDB_version, args.store_GTDB_metadata_in_current_working_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/bin/gtt-get-accessions-from-GTDB", line 593, in get_gtdb_tab
    gtdb_tab = gen_gtdb_tab("./")
               ^^^^^^^^^^^^^^^^^^
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/bin/gtt-get-accessions-from-GTDB", line 459, in gen_gtdb_tab
    gtdb_version_info = urllib.request.urlretrieve("https://data.gtdb.ecogenomic.org/releases/latest/VERSION", location + "GTDB-version-info.txt")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/lib/python3.11/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/scratch/gencore/.eb/2.0/software/gtotree/1.7.05/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
Please note that I still get an output file called `GTDB-arc-and-bac-metadata.tsv` but it only has the domain Archaea in it and no genomes from my target phylum `Actinobacteriota`.

Please let me know if you need further information from my end. Thanks!

**Comment by Ahmed-Shibl** [comment]
Update: fixed the issue. I noticed that in `/bin/gtt-get-accessions-from-GTDB` , the url reads `https://data.gtdb.ecogenomic.org/releases/latest/VERSION` rather than the correct `https://data.gtdb.ecogenomic.org/releases/latest/VERSION.txt`
Changing the two incidences where this URL is in the source file fixes the issue.

**Comment by AstrobioMike** [comment]
ah, sorry for not catching this over the weekend and leaving you hanging @Ahmed-Shibl !

Thanks for the note, it seems they changed it from just VERSION to VERSION.txt (e.g. as it is in the last release: https://data.gtdb.ecogenomic.org/releases/release202/202.0/) 

not sure how this hadn't come up yet, but i'm glad you wrote in about it! I'll fix it in the package sometime today

Thanks!

**Comment by AstrobioMike** [comment]
thanks again, @Ahmed-Shibl :) (and thanks for the kind words about gtotree too!)

Not that you need it, because you fixed it for you already, but this is updated as of v1.7.06, which is updated in my conda channel, will be in bioconda soon, this grabs the latest from my channel:

`conda create -y -n gtotree -c astrobiomike -c conda-forge -c bioconda -c defaults gtotree`

**Comment by Ahmed-Shibl** [comment]
Thank you, @AstrobioMike! I'll get this new version installed once I'm done with the exploratory analysis I started earlier.
